project:
  type: website

website:
  title: "foscraft"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/foscraft
      - icon: twitter
        href: https://twitter.com/foscraft
format:
  html:
    theme: solar
    css: styles.css



